name: Docker Image PAN-OS-PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag my-image-name:$(date +%s)
