name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Build and push pan-os-php-amd
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-main_amd
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pan-os-php-amd:${{ secrets.DOCKER_HUB_TAG }}

      -
        name: Build and push pan-os-php-cli-amd
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-php_amd
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pan-os-php-cli-amd:${{ secrets.DOCKER_HUB_TAG }}

      -
        name: Build and push pan-os-php-api-amd
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-API_amd
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pan-os-php-api-amd:${{ secrets.DOCKER_HUB_TAG }}

      -
        name: Build and push pan-os-php-cli_php8_2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-cli-ubuntu22-php8_2
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pan-os-php-cli_php8_2:${{ secrets.DOCKER_HUB_TAG }}