name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # v1

      -
        name: Build and push pan-os-php-amd
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-main_amd
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pan-os-php-amd:${{ secrets.DOCKER_HUB_TAG }}

      -
        name: Build and push pan-os-php-cli-amd
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-php_amd
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pan-os-php-cli-amd:${{ secrets.DOCKER_HUB_TAG }}

      -
        name: Build and push pan-os-php-api-amd
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-API_amd
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pan-os-php-api-amd:${{ secrets.DOCKER_HUB_TAG }}

      -
        name: Build and push pan-os-php-cli_php8_2
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2
        with:
          context: .
          file: docker/Dockerfile-cli-ubuntu22-php8_2
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pan-os-php-cli_php8_2:${{ secrets.DOCKER_HUB_TAG }}